#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "To keep prod safe, committing directly to main is verboten. Please develop in a new branch!"
  exit 1
fi

npx lint-staged
